### ISSUE TITLE
Deprecation warnings for CakePHP 3.7

### ISSUE THREAD

**Issue by OneHatRepo** [dereuromark/cakephp-setup#17]
While using this plugin with CakePHP 3.7, I get the following errors when activating maintenance mode:

Deprecated (16384): ViewBuilder::className() is deprecated. Use ViewBuilder::setClassName() or ViewBuilder::getClassName() instead. - /home/ga/public_html/vendor/dereuromark/cakephp-setup/src/Middleware/MaintenanceMiddleware.php, line: 67
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. [CORE/src/Core/functions.php, line 311]

Deprecated (16384): ViewBuilder::templatePath() is deprecated. Use ViewBuilder::setTemplatePath() or ViewBuilder::getTemplatePath() instead. - /home/ga/public_html/vendor/dereuromark/cakephp-setup/src/Middleware/MaintenanceMiddleware.php, line: 68
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. [CORE/src/Core/functions.php, line 311]

Deprecated (16384): ViewBuilder::layout() is deprecated. Use ViewBuilder::setLayout() or ViewBuilder::getLayout() instead. - /home/ga/public_html/vendor/dereuromark/cakephp-setup/src/Middleware/MaintenanceMiddleware.php, line: 69
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. [CORE/src/Core/functions.php, line 311]

**Comment by dereuromark** [comment]
Feel free to provide a PR with the fixes.
Otherwise I recommend sticking to disabled depr. warnings here.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-setup/pull/18 and maybe others will solve this soonish.
