### ISSUE TITLE
TypeError on `bin/cake db_unsigned -v`

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-setup#32]
Version: [current master branch](https://github.com/dereuromark/cakephp-setup/commit/8a9effcc953ef69adaa52820c49c9f4277323ae5)

```
[TypeError] Cake\Database\Schema\TableSchema::getColumn(): Argument #1 ($name) must be of type string, array given, called in /mypath/vendor/dereuromark/cakephp-setup/src/Command/DbUnsignedCommand.php on line 145 
```

This happens for table classes which have more than 1 primary key set like so:

```
$this->setPrimaryKey(['ftp_domain_id', 'category_id']);
```

which is needed if you have a separate table class for a belongsToMany connection containing e.g. the CounterCache behavior.

**Comment by dereuromark** [comment]
Should we exclude them for now?

**Comment by LordSimal** [comment]
would be the easiest, yes

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-setup/commit/ac16c29d7f771d40c14a9344431131c32d1f7057

**Comment by LordSimal** [comment]
Yup, works fine now.
