### ISSUE TITLE
error on init (cake3)

### ISSUE THREAD

**Issue by danielzzz** [dereuromark/cakephp-setup#4]
Hi, I have installed the cake3 branch via composer but I am getting an error about missing dependencies.
This is my console dump:
Updating dependencies (including require-dev)
  - Installing dereuromark/cakephp-shim (3.0.x-dev a5d1eaa)
    Cloning a5d1eaa7553bbd1e78c1828d2bb036ad8fcde6fb

  - Installing yangqi/htmldom (dev-master 5fac0fd)
    Cloning 5fac0fd569350c0b90f0ad7a9c54634786a5d66e

  - Installing dereuromark/cakephp-tools (dev-cake3 4563b96)
    Cloning 4563b96453163e825ac520d4d88e70ac2ec2c793

  - Installing dereuromark/cakephp-setup (dev-cake3 a508540)
    Cloning a508540cf913d756d915e396d08890bd465ef9e4

and I'm getting Tools.SessionComponent could not be found. on the home page which is a bit confusing, because cakephp-tools seems to be installed, right?...

**Comment by dereuromark** [comment]
Still an issue?
