### ISSUE TITLE
Component clearcache from url

### ISSUE THREAD

**Issue by sharkooon** [dereuromark/cakephp-setup#8]
When clearcache from url /?clearcache it returns Error: [InvalidArgumentException] The "" cache configuration does not exist.

$this->Controller->request->query('clearcache') returns: string(0) ""

so function clearCache($type = 'default') never returns $type = 'default'

**Comment by dereuromark** [comment]
Are you able to provide a fix as PR? Thank you.

**Comment by dereuromark** [comment]
Does the open PR help?
